In [1]:
import pandas as pd

In [2]:
umap_data = pd.read_feather('/data_isilon_main/isilon_images/10_MetaSystems/MetaSystemsData/Multimodal_Imaging_Daria/PIPELINE/NEWEST_RESULTS/results/UMAP_interactive/reduced_dim.feather')
expression_data = pd.read_feather('/data_isilon_main/isilon_images/10_MetaSystems/MetaSystemsData/Multimodal_Imaging_Daria/PIPELINE/NEWEST_RESULTS/results/UMAP_interactive/count_matrix.feather')
# meta_data = pd.read_feather('/data_isilon_main/isilon_images/10_MetaSystems/MetaSystemsData/Multimodal_Imaging_Daria/PIPELINE/NEWEST_RESULTS/results/UMAP_interactive/metadata.feather')
# merged_df = pd.merge(umap_data, expression_data, left_index=True, right_index=True).merge(meta_data, left_index=True, right_index=True)

In [4]:
sliced = umap_data.iloc[:100000, :]
sliced.to_feather("/home/simon_g/src/umap_dashboard/data/umap_data.feather")

In [5]:
sliced = expression_data.iloc[:100000, :]
sliced.to_feather("/home/simon_g/src/umap_dashboard/data/expression_data.feather")

In [6]:
sliced

,MPO_Y89_mean,CD44_In115_mean,CD11b_Nd142_mean,HLA-DR_Nd143_mean,PRPH_Nd144_mean,HLA-ABC_Sm147_mean,CD20_Nd148_mean,LUM_Sm149_mean,CD11c_Nd150_mean,CD24_Eu151_mean,...,CD279_Ho165_mean,GATA3_Er168_mean,Ki-67_Tm169_mean,CD56_Er170_mean,CD4_Yb171_mean,GZMB_Yb173_mean,ELAVL4_Yb174_mean,CD14_Lu175_mean,Vimentin_Pt196_mean,CD15_Bi209_mean
0,0.141667,0.000000,0.033333,0.000000,0.0,0.142857,0.000000,0.0,0.0,0.166667,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.247917
1,0.131818,0.335227,0.186364,0.339572,0.0,0.418831,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.070455
2,0.206897,0.000000,0.000000,0.000000,0.0,0.104680,0.000000,0.0,0.0,0.002463,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.160632
3,0.185455,0.000000,0.007273,0.000000,0.0,0.003247,0.000000,0.0,0.0,0.005195,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.118636
4,0.268000,0.000000,0.064000,0.000000,0.0,0.627143,0.000000,0.0,0.0,0.425714,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.316000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0.000000,0.000000,0.000000,0.183333,0.0,0.225714,0.278571,0.0,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
99996,0.352152,0.000000,0.205912,0.000000,0.0,0.056881,0.000000,0.0,0.0,0.279817,...,0.0,0.0,0.025229,0.0,0.000000,0.0,0.0,0.0,0.0,0.375247
99997,0.294521,0.054795,0.032725,0.002283,0.0,0.005479,0.000000,0.0,0.0,0.160274,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.292148
99998,0.033198,0.223684,0.031579,0.000000,0.0,0.162105,0.000000,0.0,0.0,0.017193,...,0.0,0.0,0.000000,0.0,0.239474,0.0,0.0,0.0,0.0,0.026832
99999,0.167168,0.104749,0.001862,0.208566,0.0,0.165922,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000